version: '3.8'
services:
  postgres:
    image: postgres:13.3
    ports:
      - "5432:5432" 
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: test
        POSTGRES_DB: postgres

  server: 
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes: 
      - './backend:/usr/app/backend'
      - /usr/app/node_modules
    command: npm run docker_dev
    ports:
      - "8000:8000"
    depends_on: 
      - postgres
    environment:
      PORT: 8000
      NODE_ENV: "docker"
      SESSION_SECRET: "fa6312l3&0pzjcq#x3sadopgllurz#wknu*s=o#63ouv^entei"
      CHOKIDAR_USEPOLLING: "true"

  client:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    stdin_open: true    
    volumes: 
      - ./frontend:/usr/app
      - /usr/app/node_modules
    command: npm start
    depends_on: 
      - server
    ports:
        - target: 3000
          published: 4960
          protocol: tcp
          mode: host
    # If all else fails: SKIP_PREFLIGHT_CHECK: "true"

    # npm ci
    environment:
      PROXY: "http://server:3000"
      SKIP_PREFLIGHT_CHECK: "true"
      CHOKIDAR_USEPOLLING: "true"
